import{a as p,S as g,i as n}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const L="46833359-edc83954567fc8c41d0a60462",b="https://pixabay.com/api/";async function m(t,r=1,a=15){const s=`${b}?key=${L}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{const e=await p.get(s);if(e.data.hits.length===0)throw new Error("No images found");return e.data}catch(e){throw e}}let f;function y(t){const r=document.querySelector(".gallery"),a=t.map(s=>`
    <a href="${s.largeImageURL}" class="gallery-item">
      <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      <div class="info">
        <p>Likes <span class="info-number">${s.likes}</span></p>
        <p>Views <span class="info-number">${s.views}</span></p>
        <p>Comments <span class="info-number">${s.comments}</span></p>
        <p>Downloads <span class="info-number">${s.downloads}</span></p>
      </div>
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",a),f?f.refresh():f=new g(".gallery a")}function v(){const t=document.querySelector(".gallery");t.innerHTML=""}const w=document.querySelector(".search-form"),d=document.querySelector(".loader"),i=document.querySelector(".load-more"),$=document.querySelector(".gallery");let l="",c=1,h=0;w.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.currentTarget.elements.searchQuery.value.trim(),!l){n.error({message:"Please enter a search query!"});return}c=1,d.classList.remove("hidden"),i.classList.add("hidden"),v();try{const r=await m(l,c);h=r.totalHits,y(r.hits),r.hits.length<15||r.hits.length===h?(i.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("hidden")}catch{n.error({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{d.classList.add("hidden")}});i.addEventListener("click",async()=>{c+=1,d.classList.remove("hidden");try{const t=await m(l,c);y(t.hits),c*15>=h&&(i.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results."}));const r=$.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{n.error({message:"Failed to load more images."})}finally{d.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
